services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - api
    networks:
      - blogkeeper-network
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    ports:
      - "${API_PORT}:8000"
    networks:
      - blogkeeper-network
    restart: unless-stopped

networks:
  blogkeeper-network:
    driver: bridge